# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  #create first vm ubuntu
  config.vm.define "ubuntu_vm1" do |node1|
    node1.vm.box = "ubuntu/focal64"
    
    node1.vm.provider :virtualbox do |vb|
      vb.name = "ubuntu_vm1"
      vb.memory = "1024"
      vb.cpus = "1"
    end
    node1.vm.hostname = "vm1"
    node1.vm.network "private_network",
      ip: "192.168.33.10",
      netmask: "24"
    node1.vm.provision "Shell", type: "shell", run: "once" do |sh|
      shell = <<-SHELL
        SHELL
      sh.inline = shell
      sh.privileged = true
    end
  end

  #create second vm debian
  config.vm.define "debian_vm2" do |node1|
    node2.vm.box = "debian/buster64"
    node2.vm.synced_folder "./files/", "/vagrant"
    node2.vm.provider :virtualbox do |vb|
      vb.name = "debian_vm2"
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      vb.memory = "4096"
      vb.cpus = "1"
    end
    node2.vm.hostname = "vm2"
    node2.vm.network "private_network",
      ip: "192.168.33.20",
      # netmask: "24",
      auto_config: false
    
    
    node2.vm.provision "Shell", type: "shell", run: "once" do |sh|
      shell = <<-SHELL
      apt-get update
      apt-get install -y gnupg2 software-properties-common
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

      apt-get update
      apt-get install -y qemu-kvm qemu-system \
        qemu-utils libvirt-clients \
        libvirt-daemon-system virtinst libvirt-dev \
        bridge-utils \
        nfs-common nfs-kernel-server \
        build-essential vagrant
          
      systemctl enable libvirtd
      systemctl start libvirtd

      vagrant plugin install vagrant-libvirt
      sudo gpasswd -a "$USER" libvirt

      vagrant box add --provider libvirt --box-version 8.11.0  debian/jessie64

      /sbin/brctl addbr br0
      /sbin/brctl setageing br0 0
      /sbin/brctl addif br0 eth1
      ip address add 192.168.33.25/24 dev br0
      ip link set br0 up
      ip link set eth1 up
      

      cd /vagrant
      vagrant up

      SHELL
      sh.inline = shell
      sh.privileged = true
     end
  end
end
