# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/bionic64"
    node1.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    node1.vm.hostname = "alex1"
    node1.vm.network "private_network", ip: "192.168.33.2", virtualbox__intnet: "network1"

    node1.vm.provision "Go!", type: "shell", run: "always" do |sh|
      shell = "
        apt-get update
        apt-get install -y git
      "
      sh.inline = shell  
      sh.privileged = true
    end
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "ubuntu/bionic64"
    node2.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    node2.vm.hostname = "alex2"
    node2.vm.network "private_network", ip: "192.168.33.3", virtualbox__intnet: "network1"

    node2.vm.provision "Go!", type: "shell", run: "once" do |sh|
      shell = "
        
      "
      sh.inline = shell
    end
  end
end